/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main;

import java.awt.Desktop;
import java.awt.event.WindowEvent;
import java.io.IOException;
import java.net.URI;
import java.net.URISyntaxException;

/**
 * 
 * @author HJianFei
 */
public class WarnFrame extends javax.swing.JFrame {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * Creates new form WarnFrame
	 */
	public WarnFrame() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	// <editor-fold defaultstate="collapsed"
	// desc="Generated Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jLabel1 = new javax.swing.JLabel();
		btn_look = new javax.swing.JButton();
		btn_after = new javax.swing.JButton();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		jLabel1.setFont(new java.awt.Font("宋体", 0, 24)); // NOI18N
		jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		jLabel1.setText("有货物被盗了，请及时查看。");

		btn_look.setFont(new java.awt.Font("宋体", 0, 18)); // NOI18N
		btn_look.setText("立即查看");
		btn_look.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btn_lookActionPerformed(evt);
			}
		});

		btn_after.setFont(new java.awt.Font("宋体", 0, 18)); // NOI18N
		btn_after.setText("稍后处理");
		btn_after.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btn_afterActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						javax.swing.GroupLayout.Alignment.TRAILING,
						layout.createSequentialGroup()
								.addContainerGap(95, Short.MAX_VALUE)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING)
												.addGroup(
														layout.createSequentialGroup()
																.addComponent(
																		btn_look,
																		javax.swing.GroupLayout.PREFERRED_SIZE,
																		123,
																		javax.swing.GroupLayout.PREFERRED_SIZE)
																.addGap(42, 42,
																		42)
																.addComponent(
																		btn_after,
																		javax.swing.GroupLayout.PREFERRED_SIZE,
																		131,
																		javax.swing.GroupLayout.PREFERRED_SIZE))
												.addComponent(jLabel1))
								.addGap(91, 91, 91)));
		layout.setVerticalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addContainerGap(58, Short.MAX_VALUE)
								.addComponent(jLabel1)
								.addGap(38, 38, 38)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING,
												false)
												.addComponent(
														btn_look,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														40, Short.MAX_VALUE)
												.addComponent(
														btn_after,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														Short.MAX_VALUE))
								.addGap(35, 35, 35)));

		setSize(new java.awt.Dimension(514, 239));
		setLocationRelativeTo(null);
	}// </editor-fold>//GEN-END:initComponents

	private void btn_lookActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btn_lookActionPerformed
		// TODO add your handling code here:
		Desktop desktop = Desktop.getDesktop();
		try {
			desktop.browse(new URI("http://www.baidu.com"));
//			this.dispatchEvent(new WindowEvent(this, WindowEvent.WINDOW_CLOSING));
		} catch (IOException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		} catch (URISyntaxException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}

	}// GEN-LAST:event_btn_lookActionPerformed

	private void btn_afterActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btn_afterActionPerformed
		// TODO add your handling code here:
		this.dispatchEvent(new WindowEvent(this, WindowEvent.WINDOW_CLOSING));
	}// GEN-LAST:event_btn_afterActionPerformed

	/**
	 * @param args
	 *            the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed"
		// desc=" Look and feel setting code (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the
		 * default look and feel. For details see
		 * http://download.oracle.com/javase
		 * /tutorial/uiswing/lookandfeel/plaf.html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager
					.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(WarnFrame.class.getName()).log(
					java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(WarnFrame.class.getName()).log(
					java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(WarnFrame.class.getName()).log(
					java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(WarnFrame.class.getName()).log(
					java.util.logging.Level.SEVERE, null, ex);
		}
		// </editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new WarnFrame().setVisible(true);
			}
		});
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton btn_after;
	private javax.swing.JButton btn_look;
	private javax.swing.JLabel jLabel1;
	// End of variables declaration//GEN-END:variables
}
