/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frame;

import java.applet.Applet;
import java.applet.AudioClip;
import java.awt.Desktop;
import java.awt.Toolkit;
import java.io.BufferedReader;
import java.io.FileInputStream;
import java.io.InputStreamReader;
import java.net.MalformedURLException;
import java.net.URI;
import java.net.URL;
import java.util.ArrayList;
import java.util.List;

import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

import client.Listener;

/**
 * 
 * @author HJianFei
 */
public class MainFrame extends javax.swing.JFrame {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	// private AudioClip clip;

	/**
	 * Creates new form MainFrame
	 */
	public MainFrame() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	// <editor-fold defaultstate="collapsed"
	// desc="Generated Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		menuBar1 = new java.awt.MenuBar();
		menu1 = new java.awt.Menu();
		menu2 = new java.awt.Menu();
		jLabel1 = new javax.swing.JLabel();
		btn_start = new javax.swing.JButton();
		jLabel = new javax.swing.JLabel();
		btn_look = new javax.swing.JButton();
		label_text = new javax.swing.JLabel();
		jMenuBar2 = new javax.swing.JMenuBar();
		jMenu3 = new javax.swing.JMenu();
		option_menu = new javax.swing.JMenuItem();
		option_exit = new javax.swing.JMenuItem();

		menu1.setLabel("File");
		menuBar1.add(menu1);

		menu2.setLabel("Edit");
		menuBar1.add(menu2);

		setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
		setTitle("智能防盗系统");

		jLabel1.setFont(new java.awt.Font("宋体", 0, 48)); // NOI18N
		jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		jLabel1.setText("智能防盗");
		jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

		btn_start.setFont(new java.awt.Font("宋体", 0, 24)); // NOI18N
		btn_start.setText("启动程序");
		btn_start.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btn_startActionPerformed(evt);
			}
		});

		jLabel.setBackground(new java.awt.Color(0, 0, 0));
		jLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		jLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
		btn_look.setEnabled(false);
		btn_look.setFont(new java.awt.Font("宋体", 0, 36)); // NOI18N
		btn_look.setText("有货物被盗了，立即处理");
		btn_look.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
		btn_look.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				try {
					btn_lookActionPerformed(evt);
				} catch (Exception e) {
					e.printStackTrace();
				}
			}
		});

		label_text.setFont(new java.awt.Font("宋体", 0, 18)); // NOI18N
		label_text.setForeground(new java.awt.Color(255, 0, 0));
		label_text.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		label_text.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

		jLabel.setIcon(new ImageIcon(MainFrame.class
				.getResource("/image/login.jpg")));
		jMenu3.setText("系统设置");

		option_menu.setText("参数设置");
		option_menu.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				option_menuActionPerformed(evt);
			}
		});
		jMenu3.add(option_menu);

		option_exit.setText("退出系统");
		option_exit.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				option_exitActionPerformed(evt);
			}
		});
		jMenu3.add(option_exit);

		jMenuBar2.add(jMenu3);

		setJMenuBar(jMenuBar2);

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						javax.swing.GroupLayout.Alignment.TRAILING,
						layout.createSequentialGroup()
								.addGap(217, 217, 217)
								.addComponent(jLabel,
										javax.swing.GroupLayout.DEFAULT_SIZE,
										953, Short.MAX_VALUE)
								.addGap(214, 214, 214))
				.addGroup(
						layout.createSequentialGroup()
								.addGap(49, 49, 49)
								.addComponent(btn_look,
										javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE,
										Short.MAX_VALUE).addGap(61, 61, 61))
				.addGroup(
						layout.createSequentialGroup()
								.addGap(579, 579, 579)
								.addComponent(btn_start,
										javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE,
										Short.MAX_VALUE).addGap(557, 557, 557))
				.addGroup(
						layout.createSequentialGroup()
								.addGap(41, 41, 41)
								.addComponent(jLabel1,
										javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE,
										Short.MAX_VALUE).addGap(53, 53, 53))
				.addGroup(
						javax.swing.GroupLayout.Alignment.TRAILING,
						layout.createSequentialGroup()
								.addGap(467, 467, 467)
								.addComponent(label_text,
										javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE,
										Short.MAX_VALUE).addGap(443, 443, 443)));
		layout.setVerticalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addGap(25, 25, 25)
								.addComponent(jLabel1)
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addComponent(jLabel,
										javax.swing.GroupLayout.PREFERRED_SIZE,
										320,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.RELATED,
										32, Short.MAX_VALUE)
								.addComponent(btn_look,
										javax.swing.GroupLayout.PREFERRED_SIZE,
										121,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addGap(18, 18, 18)
								.addComponent(btn_start,
										javax.swing.GroupLayout.PREFERRED_SIZE,
										48,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addGap(18, 18, 18)
								.addComponent(label_text,
										javax.swing.GroupLayout.PREFERRED_SIZE,
										46,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addContainerGap()));

		double width = Toolkit.getDefaultToolkit().getScreenSize().width; // 得到当前屏幕分辨率的高
		double height = Toolkit.getDefaultToolkit().getScreenSize().height;// 得到当前屏幕分辨率的宽
		this.setSize((int) width, (int) height);// 设置大小
		this.setLocation(0, 0); // 设置窗体居中显示
		this.setResizable(false);// 禁用最大化按钮
	}// </editor-fold>//GEN-END:initComponents

	private void option_menuActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_option_menuActionPerformed
		// TODO add your handling code here:
		new SettingFrame().setVisible(true);

	}// GEN-LAST:event_option_menuActionPerformed

	private void btn_startActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btn_startActionPerformed
		// TODO add your handling code here:
		// startMusic();
		URL musicUrl;
		try {
			musicUrl = new URL(MainFrame.class.getResource("/music/warn.mid")
					+ "");
			ac = Applet.newAudioClip(musicUrl);
		} catch (MalformedURLException e1) {
			// TODO Auto-generated catch block
			e1.printStackTrace();
		} // 音乐URL

		InputStreamReader isr;
		try {
			isr = new InputStreamReader(new FileInputStream(
					MainFrame.class.getResource("/files/Myfile.txt") + ""),
					"utf-8");
			BufferedReader read = new BufferedReader(isr);
			String s = null;
			list = new ArrayList<String>();
			while ((s = read.readLine()) != null) {
				if (s.trim().length() > 1) {
					list.add(s.trim());
				}
			}
			Listener listener = new Listener(list.get(0), list.get(1),
					list.get(2), btn_start, btn_look, label_text, ac);
			String flag = listener.startListener();
			if ("OK".equals(flag)) {
				btn_start.setEnabled(false);
				label_text.setText("程序已启动！");
			} else {
				label_text.setText("程序启动失败，请重试");
			}
		} catch (Exception e) {
			e.printStackTrace();
			JOptionPane.showMessageDialog(null, "参数设置失败,请重新设置参数", "参数缺失",
					JOptionPane.INFORMATION_MESSAGE);
		}
	}

	private void option_exitActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_option_exitActionPerformed
		System.exit(0);
	}

	private void btn_lookActionPerformed(java.awt.event.ActionEvent evt)
			throws Exception {
		Desktop desktop = Desktop.getDesktop();
		String uri = "http://" + list.get(5)
				+ ":8080/cargosys/pc/loginToWarn?u=" + list.get(3) + "&pd="
				+ list.get(4);
		desktop.browse(new URI(uri));
		btn_look.setEnabled(false);
		ac.stop();

	}

	/**
	 * @param args
	 *            the command line arguments
	 */
	public static void main(String args[]) {
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager
					.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(
					java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(
					java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(
					java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(
					java.util.logging.Level.SEVERE, null, ex);
		}
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new MainFrame().setVisible(true);
			}
		});
	}

	private javax.swing.JButton btn_look;
	private javax.swing.JButton btn_start;
	private javax.swing.JLabel jLabel;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JMenu jMenu3;
	private javax.swing.JMenuBar jMenuBar2;
	private javax.swing.JLabel label_text;
	private java.awt.Menu menu1;
	private java.awt.Menu menu2;
	private java.awt.MenuBar menuBar1;
	private javax.swing.JMenuItem option_exit;
	private javax.swing.JMenuItem option_menu;
	private List<String> list;
	private AudioClip ac;
}
