/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frame;

import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;

import javax.swing.JOptionPane;

import utils.DesEncrypt;

/**
 * 
 * @author HJianFei
 */
public class SettingFrame extends javax.swing.JFrame {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * Creates new form SettingFrame
	 */
	public SettingFrame() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	// <editor-fold defaultstate="collapsed"
	// desc="Generated Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jLabel1 = new javax.swing.JLabel();
		jLabel2 = new javax.swing.JLabel();
		client_name = new javax.swing.JTextField();
		jLabel3 = new javax.swing.JLabel();
		server_ip = new javax.swing.JTextField();
		jLabel4 = new javax.swing.JLabel();
		port = new javax.swing.JTextField();
		jLabel5 = new javax.swing.JLabel();
		topic = new javax.swing.JTextField();
		jLabel6 = new javax.swing.JLabel();
		user_name = new javax.swing.JTextField();
		jLabel7 = new javax.swing.JLabel();
		user_password = new javax.swing.JPasswordField();
		btn_ok = new javax.swing.JButton();
		btn_cancel = new javax.swing.JButton();

		setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

		jLabel1.setFont(new java.awt.Font("宋体", 0, 18)); // NOI18N
		jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		jLabel1.setText("系统参数设置");
		jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

		jLabel2.setFont(new java.awt.Font("宋体", 0, 14)); // NOI18N
		jLabel2.setText("客户端名称：");

		client_name.setFont(new java.awt.Font("宋体", 0, 14)); // NOI18N

		jLabel3.setFont(new java.awt.Font("宋体", 0, 14)); // NOI18N
		jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		jLabel3.setText("服务器IP地址：");

		server_ip.setFont(new java.awt.Font("宋体", 0, 14)); // NOI18N

		jLabel4.setFont(new java.awt.Font("宋体", 0, 14)); // NOI18N
		jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		jLabel4.setText("服务器端口：");

		port.setFont(new java.awt.Font("宋体", 0, 14)); // NOI18N

		jLabel5.setFont(new java.awt.Font("宋体", 0, 14)); // NOI18N
		jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		jLabel5.setText("订阅主题：");

		topic.setFont(new java.awt.Font("宋体", 0, 14)); // NOI18N

		jLabel6.setFont(new java.awt.Font("宋体", 0, 14)); // NOI18N
		jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		jLabel6.setText("用户名：");

		user_name.setFont(new java.awt.Font("宋体", 0, 14)); // NOI18N

		jLabel7.setFont(new java.awt.Font("宋体", 0, 14)); // NOI18N
		jLabel7.setText("密码：");

		user_password.setFont(new java.awt.Font("宋体", 0, 14)); // NOI18N
		user_password.setHorizontalAlignment(javax.swing.JTextField.LEFT);

		btn_ok.setFont(new java.awt.Font("宋体", 0, 14)); // NOI18N
		btn_ok.setText("确定");
		btn_ok.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btn_okActionPerformed(evt);
			}
		});

		btn_cancel.setFont(new java.awt.Font("宋体", 0, 14)); // NOI18N
		btn_cancel.setText("取消");
		btn_cancel.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				btn_cancelActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						javax.swing.GroupLayout.Alignment.TRAILING,
						layout.createSequentialGroup()
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.TRAILING)
												.addGroup(
														layout.createSequentialGroup()
																.addGap(100,
																		100,
																		100)
																.addComponent(
																		jLabel1,
																		javax.swing.GroupLayout.DEFAULT_SIZE,
																		217,
																		Short.MAX_VALUE))
												.addGroup(
														layout.createSequentialGroup()
																.addGroup(
																		layout.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.TRAILING)
																				.addGroup(
																						javax.swing.GroupLayout.Alignment.LEADING,
																						layout.createSequentialGroup()
																								.addGap(81,
																										81,
																										81)
																								.addComponent(
																										jLabel2)
																								.addGap(18,
																										18,
																										18)
																								.addComponent(
																										client_name))
																				.addGroup(
																						javax.swing.GroupLayout.Alignment.LEADING,
																						layout.createSequentialGroup()
																								.addGap(70,
																										70,
																										70)
																								.addGroup(
																										layout.createParallelGroup(
																												javax.swing.GroupLayout.Alignment.TRAILING)
																												.addComponent(
																														jLabel3)
																												.addComponent(
																														jLabel4)
																												.addComponent(
																														jLabel5))
																								.addGap(18,
																										18,
																										18)
																								.addGroup(
																										layout.createParallelGroup(
																												javax.swing.GroupLayout.Alignment.LEADING)
																												.addComponent(
																														server_ip)
																												.addComponent(
																														port)
																												.addComponent(
																														topic))))
																.addGap(8, 8, 8)))
								.addGap(83, 83, 83))
				.addGroup(
						layout.createSequentialGroup()
								.addGap(46, 46, 46)
								.addComponent(jLabel6)
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING)
												.addComponent(
														user_name,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														81,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(
														btn_ok,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														81,
														javax.swing.GroupLayout.PREFERRED_SIZE))
								.addGap(18, 18, 18)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING)
												.addGroup(
														layout.createSequentialGroup()
																.addComponent(
																		jLabel7)
																.addPreferredGap(
																		javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																.addComponent(
																		user_password,
																		javax.swing.GroupLayout.PREFERRED_SIZE,
																		95,
																		javax.swing.GroupLayout.PREFERRED_SIZE))
												.addGroup(
														layout.createSequentialGroup()
																.addGap(10, 10,
																		10)
																.addComponent(
																		btn_cancel,
																		javax.swing.GroupLayout.PREFERRED_SIZE,
																		84,
																		javax.swing.GroupLayout.PREFERRED_SIZE)))
								.addContainerGap(
										javax.swing.GroupLayout.DEFAULT_SIZE,
										Short.MAX_VALUE)));
		layout.setVerticalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						layout.createSequentialGroup()
								.addContainerGap()
								.addComponent(jLabel1,
										javax.swing.GroupLayout.DEFAULT_SIZE,
										29, Short.MAX_VALUE)
								.addGap(18, 18, 18)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(jLabel2)
												.addComponent(
														client_name,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE))
								.addGap(18, 18, 18)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(jLabel3)
												.addComponent(
														server_ip,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE))
								.addGap(18, 18, 18)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(jLabel4)
												.addComponent(
														port,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE))
								.addGap(18, 18, 18)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(jLabel5)
												.addComponent(
														topic,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE))
								.addGap(18, 18, 18)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(jLabel6)
												.addComponent(
														user_name,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE)
												.addComponent(jLabel7)
												.addComponent(
														user_password,
														javax.swing.GroupLayout.PREFERRED_SIZE,
														javax.swing.GroupLayout.DEFAULT_SIZE,
														javax.swing.GroupLayout.PREFERRED_SIZE))
								.addPreferredGap(
										javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
								.addGroup(
										layout.createParallelGroup(
												javax.swing.GroupLayout.Alignment.BASELINE)
												.addComponent(btn_cancel)
												.addComponent(btn_ok))
								.addGap(26, 26, 26)));

		setSize(new java.awt.Dimension(416, 339));
		setLocationRelativeTo(null);
	}// </editor-fold>//GEN-END:initComponents

	private void btn_okActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btn_okActionPerformed
		// TODO add your handling code here:
		CLIENT_NAME = client_name.getText().toString().trim();
		SERVER_IP = server_ip.getText().toString().trim();
		PORT = port.getText().toString().trim();
		TOPIC = topic.getText().toString().trim();
		userName = user_name.getText().toString().trim();
		passWord = user_password.getPassword();
		if (CLIENT_NAME.isEmpty() || SERVER_IP.isEmpty() || PORT.isEmpty()
				|| TOPIC.isEmpty() || userName.isEmpty()
				|| passWord.length <= 0) {
			JOptionPane.showMessageDialog(null,
					"客户端名称 or 服务器IP地址 or 服务器端口 or 订阅主题 or 用户名  or 密码 不能为空",
					"错误提示", JOptionPane.ERROR_MESSAGE);
			return;
		}
		HOST = "tcp://" + SERVER_IP + ":" + PORT;
		int flag = writeFile(HOST, SERVER_IP, TOPIC, CLIENT_NAME, userName,
				passWord);
		if (flag == 1) {
			JOptionPane.showMessageDialog(null, "参数设置成功", "参数设置",
					JOptionPane.INFORMATION_MESSAGE);
			this.dispose();
		} else {
			JOptionPane.showMessageDialog(null, "参数设置失败", "参数设置",
					JOptionPane.INFORMATION_MESSAGE);

		}
	}// GEN-LAST:event_btn_okActionPerformed

	private int writeFile(String host, String server_ip, String topic,
			String client_name, String userName, char[] passWord) {
		// TODO Auto-generated method stub
		FileOutputStream fop = null;
		File file;
		DesEncrypt desEncrypt = new DesEncrypt();
		String pad = desEncrypt.encrypt(String.valueOf(passWord));
		String content = host + "\n" + topic + "\n" + client_name + "\n"
				+ userName + "\n" + pad + "\n" + server_ip;
		try {
//			System.out.println(SettingFrame.class.getResource("/files/Myfile.txt") + "");
			file = new File(SettingFrame.class.getResource("/files/Myfile.txt") + "");
			fop = new FileOutputStream(file); // if file doesnt exists, then
												// create it
			if (!file.exists()) {
				file.createNewFile();
			}
			// get the content in bytes
			byte[] contentInBytes = content.getBytes();
			fop.write(contentInBytes);
			fop.flush();
			fop.close();
		} catch (IOException e) {
			e.printStackTrace();
			return 0;
		} finally {
			try {
				if (fop != null) {
					fop.close();
				}
			} catch (IOException e) {
				e.printStackTrace();
			}
		}
		return 1;

	}

	private void btn_cancelActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btn_cancelActionPerformed
		// TODO add your handling code here:
		this.dispose();
	}// GEN-LAST:event_btn_cancelActionPerformed

	/**
	 * @param args
	 *            the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed"
		// desc=" Look and feel setting code (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the
		 * default look and feel. For details see
		 * http://download.oracle.com/javase
		 * /tutorial/uiswing/lookandfeel/plaf.html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager
					.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(SettingFrame.class.getName())
					.log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(SettingFrame.class.getName())
					.log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(SettingFrame.class.getName())
					.log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(SettingFrame.class.getName())
					.log(java.util.logging.Level.SEVERE, null, ex);
		}
		// </editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new SettingFrame().setVisible(true);
			}
		});
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton btn_cancel;
	private javax.swing.JButton btn_ok;
	private javax.swing.JTextField client_name;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel3;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JLabel jLabel5;
	private javax.swing.JLabel jLabel6;
	private javax.swing.JLabel jLabel7;
	private javax.swing.JTextField port;
	private javax.swing.JTextField server_ip;
	private javax.swing.JTextField topic;
	private javax.swing.JTextField user_name;
	private javax.swing.JPasswordField user_password;
	private String HOST = "";
	private String SERVER_IP = "";
	private String TOPIC = "";
	private String CLIENT_NAME = "";
	private String PORT = "";
	private String userName = "";
	private char[] passWord;
	// End of variables declaration//GEN-END:variables
}
